// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models/company.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Profile struct {
	AboutMe           string   `protobuf:"bytes,1,opt,name=about_me,json=aboutMe,proto3" json:"about_me,omitempty"`
	Activities        []string `protobuf:"bytes,2,rep,name=activities,proto3" json:"activities,omitempty"`
	AffiliationCount  uint64   `protobuf:"varint,3,opt,name=affiliation_count,json=affiliationCount,proto3" json:"affiliation_count,omitempty"`
	Birthday          string   `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	FavoriteBooks     []string `protobuf:"bytes,5,rep,name=favorite_books,json=favoriteBooks,proto3" json:"favorite_books,omitempty"`
	FavoriteMovies    []string `protobuf:"bytes,6,rep,name=favorite_movies,json=favoriteMovies,proto3" json:"favorite_movies,omitempty"`
	FavoriteMusic     []string `protobuf:"bytes,7,rep,name=favorite_music,json=favoriteMusic,proto3" json:"favorite_music,omitempty"`
	FavoriteQuotes    []string `protobuf:"bytes,8,rep,name=favorite_quotes,json=favoriteQuotes,proto3" json:"favorite_quotes,omitempty"`
	FavoriteTvShoes   []string `protobuf:"bytes,9,rep,name=favorite_tv_shoes,json=favoriteTvShoes,proto3" json:"favorite_tv_shoes,omitempty"`
	FirstName         string   `protobuf:"bytes,10,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Interests         []string `protobuf:"bytes,11,rep,name=interests,proto3" json:"interests,omitempty"`
	IsApplicationUser bool     `protobuf:"varint,12,opt,name=is_application_user,json=isApplicationUser,proto3" json:"is_application_user,omitempty"`
	LastName          string   `protobuf:"bytes,13,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	NotesCount        uint64   `protobuf:"varint,14,opt,name=notes_count,json=notesCount,proto3" json:"notes_count,omitempty"`
	PictureBigUrl     string   `protobuf:"bytes,15,opt,name=picture_big_url,json=pictureBigUrl,proto3" json:"picture_big_url,omitempty"`
	PictureSmallUrl   string   `protobuf:"bytes,16,opt,name=picture_small_url,json=pictureSmallUrl,proto3" json:"picture_small_url,omitempty"`
	PictureUrl        string   `protobuf:"bytes,17,opt,name=picture_url,json=pictureUrl,proto3" json:"picture_url,omitempty"`
	PoliticalViews    []string `protobuf:"bytes,18,rep,name=political_views,json=politicalViews,proto3" json:"political_views,omitempty"`
	Religion          string   `protobuf:"bytes,19,opt,name=religion,proto3" json:"religion,omitempty"`
	SchoolCount       uint64   `protobuf:"varint,20,opt,name=school_count,json=schoolCount,proto3" json:"school_count,omitempty"`
	WallCount         uint64   `protobuf:"varint,21,opt,name=wall_count,json=wallCount,proto3" json:"wall_count,omitempty"`
	// @inject_tag: cb_referenced:"profile_status"
	Status *Status `protobuf:"bytes,22,opt,name=status,proto3" json:"status,omitempty" cb_referenced:"profile_status"`
	// @inject_tag: cb_referenced:"profile_primary_school"
	PrimarySchool *School `protobuf:"bytes,23,opt,name=primary_school,json=primarySchool,proto3" json:"primary_school,omitempty" cb_referenced:"profile_primary_school"`
	// @inject_tag: cb_referenced:"profile_high_school"
	HighSchool *School `protobuf:"bytes,24,opt,name=high_school,json=highSchool,proto3" json:"high_school,omitempty" cb_referenced:"profile_high_school"`
	// @inject_tag: cb_referenced:"profile_location"
	Location *Location `protobuf:"bytes,25,opt,name=location,proto3" json:"location,omitempty" cb_referenced:"profile_location"`
	// @inject_tag: cb_referenced:"profile_photo"
	Photo                *Photo   `protobuf:"bytes,26,opt,name=photo,proto3" json:"photo,omitempty" cb_referenced:"profile_photo"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_23892fbc74a85022, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetAboutMe() string {
	if m != nil {
		return m.AboutMe
	}
	return ""
}

func (m *Profile) GetActivities() []string {
	if m != nil {
		return m.Activities
	}
	return nil
}

func (m *Profile) GetAffiliationCount() uint64 {
	if m != nil {
		return m.AffiliationCount
	}
	return 0
}

func (m *Profile) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *Profile) GetFavoriteBooks() []string {
	if m != nil {
		return m.FavoriteBooks
	}
	return nil
}

func (m *Profile) GetFavoriteMovies() []string {
	if m != nil {
		return m.FavoriteMovies
	}
	return nil
}

func (m *Profile) GetFavoriteMusic() []string {
	if m != nil {
		return m.FavoriteMusic
	}
	return nil
}

func (m *Profile) GetFavoriteQuotes() []string {
	if m != nil {
		return m.FavoriteQuotes
	}
	return nil
}

func (m *Profile) GetFavoriteTvShoes() []string {
	if m != nil {
		return m.FavoriteTvShoes
	}
	return nil
}

func (m *Profile) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Profile) GetInterests() []string {
	if m != nil {
		return m.Interests
	}
	return nil
}

func (m *Profile) GetIsApplicationUser() bool {
	if m != nil {
		return m.IsApplicationUser
	}
	return false
}

func (m *Profile) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Profile) GetNotesCount() uint64 {
	if m != nil {
		return m.NotesCount
	}
	return 0
}

func (m *Profile) GetPictureBigUrl() string {
	if m != nil {
		return m.PictureBigUrl
	}
	return ""
}

func (m *Profile) GetPictureSmallUrl() string {
	if m != nil {
		return m.PictureSmallUrl
	}
	return ""
}

func (m *Profile) GetPictureUrl() string {
	if m != nil {
		return m.PictureUrl
	}
	return ""
}

func (m *Profile) GetPoliticalViews() []string {
	if m != nil {
		return m.PoliticalViews
	}
	return nil
}

func (m *Profile) GetReligion() string {
	if m != nil {
		return m.Religion
	}
	return ""
}

func (m *Profile) GetSchoolCount() uint64 {
	if m != nil {
		return m.SchoolCount
	}
	return 0
}

func (m *Profile) GetWallCount() uint64 {
	if m != nil {
		return m.WallCount
	}
	return 0
}

func (m *Profile) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Profile) GetPrimarySchool() *School {
	if m != nil {
		return m.PrimarySchool
	}
	return nil
}

func (m *Profile) GetHighSchool() *School {
	if m != nil {
		return m.HighSchool
	}
	return nil
}

func (m *Profile) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Profile) GetPhoto() *Photo {
	if m != nil {
		return m.Photo
	}
	return nil
}

type Status struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UpdateTime           string   `protobuf:"bytes,2,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_23892fbc74a85022, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Status) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type School struct {
	Concentrations       []string `protobuf:"bytes,1,rep,name=concentrations,proto3" json:"concentrations,omitempty"`
	GraduationYear       uint64   `protobuf:"varint,2,opt,name=graduation_year,json=graduationYear,proto3" json:"graduation_year,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *School) Reset()         { *m = School{} }
func (m *School) String() string { return proto.CompactTextString(m) }
func (*School) ProtoMessage()    {}
func (*School) Descriptor() ([]byte, []int) {
	return fileDescriptor_23892fbc74a85022, []int{2}
}

func (m *School) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_School.Unmarshal(m, b)
}
func (m *School) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_School.Marshal(b, m, deterministic)
}
func (m *School) XXX_Merge(src proto.Message) {
	xxx_messageInfo_School.Merge(m, src)
}
func (m *School) XXX_Size() int {
	return xxx_messageInfo_School.Size(m)
}
func (m *School) XXX_DiscardUnknown() {
	xxx_messageInfo_School.DiscardUnknown(m)
}

var xxx_messageInfo_School proto.InternalMessageInfo

func (m *School) GetConcentrations() []string {
	if m != nil {
		return m.Concentrations
	}
	return nil
}

func (m *School) GetGraduationYear() uint64 {
	if m != nil {
		return m.GraduationYear
	}
	return 0
}

func (m *School) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Location struct {
	City                 string   `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Street               string   `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	ZipCode              string   `protobuf:"bytes,5,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_23892fbc74a85022, []int{3}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Location) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Location) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Location) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *Location) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

type Photo struct {
	Caption              string   `protobuf:"bytes,1,opt,name=caption,proto3" json:"caption,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LargeSource          string   `protobuf:"bytes,3,opt,name=large_source,json=largeSource,proto3" json:"large_source,omitempty"`
	Link                 string   `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	MediumSource         string   `protobuf:"bytes,5,opt,name=medium_source,json=mediumSource,proto3" json:"medium_source,omitempty"`
	SmallSource          string   `protobuf:"bytes,6,opt,name=small_source,json=smallSource,proto3" json:"small_source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Photo) Reset()         { *m = Photo{} }
func (m *Photo) String() string { return proto.CompactTextString(m) }
func (*Photo) ProtoMessage()    {}
func (*Photo) Descriptor() ([]byte, []int) {
	return fileDescriptor_23892fbc74a85022, []int{4}
}

func (m *Photo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Photo.Unmarshal(m, b)
}
func (m *Photo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Photo.Marshal(b, m, deterministic)
}
func (m *Photo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Photo.Merge(m, src)
}
func (m *Photo) XXX_Size() int {
	return xxx_messageInfo_Photo.Size(m)
}
func (m *Photo) XXX_DiscardUnknown() {
	xxx_messageInfo_Photo.DiscardUnknown(m)
}

var xxx_messageInfo_Photo proto.InternalMessageInfo

func (m *Photo) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *Photo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Photo) GetLargeSource() string {
	if m != nil {
		return m.LargeSource
	}
	return ""
}

func (m *Photo) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Photo) GetMediumSource() string {
	if m != nil {
		return m.MediumSource
	}
	return ""
}

func (m *Photo) GetSmallSource() string {
	if m != nil {
		return m.SmallSource
	}
	return ""
}

type Event struct {
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	EndTime     string `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SubType     string `protobuf:"bytes,3,opt,name=sub_type,json=subType,proto3" json:"sub_type,omitempty"`
	Type        string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Host        string `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	// @inject_tag: cb_referenced:"event_photo"
	Photo *Photo `protobuf:"bytes,6,opt,name=photo,proto3" json:"photo,omitempty" cb_referenced:"event_photo"`
	// @inject_tag: cb_referenced:"event_location"
	Location             *Location `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty" cb_referenced:"event_location"`
	Name                 string    `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	StartTime            string    `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_23892fbc74a85022, []int{5}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *Event) GetSubType() string {
	if m != nil {
		return m.SubType
	}
	return ""
}

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Event) GetPhoto() *Photo {
	if m != nil {
		return m.Photo
	}
	return nil
}

func (m *Event) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

type Order struct {
	Token                 string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CreationDate          string `protobuf:"bytes,2,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	ModificationDate      string `protobuf:"bytes,3,opt,name=modification_date,json=modificationDate,proto3" json:"modification_date,omitempty"`
	Status                string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	PaymentMethod         string `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	InvoiceNumber         string `protobuf:"bytes,6,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	Email                 string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	CardholderName        string `protobuf:"bytes,8,opt,name=cardholder_name,json=cardholderName,proto3" json:"cardholder_name,omitempty"`
	CreditCardLast4Digits string `protobuf:"bytes,9,opt,name=credit_card_last4digits,json=creditCardLast4digits,proto3" json:"credit_card_last4digits,omitempty"`
	// @inject_tag: cb_referenced:"order_billing_address_location"
	BillingAddress      *Location `protobuf:"bytes,10,opt,name=billing_address,json=billingAddress,proto3" json:"billing_address,omitempty" cb_referenced:"order_billing_address_location"`
	BillingAddressName  string    `protobuf:"bytes,11,opt,name=billing_address_name,json=billingAddressName,proto3" json:"billing_address_name,omitempty"`
	BillingAddressPhone string    `protobuf:"bytes,18,opt,name=billing_address_phone,json=billingAddressPhone,proto3" json:"billing_address_phone,omitempty"`
	Notes               string    `protobuf:"bytes,19,opt,name=notes,proto3" json:"notes,omitempty"`
	ShippingAddressName string    `protobuf:"bytes,20,opt,name=shipping_address_name,json=shippingAddressName,proto3" json:"shipping_address_name,omitempty"`
	// @inject_tag: cb_referenced:"order_shipping_address_location"
	ShippingAddress              *Location `protobuf:"bytes,21,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty" cb_referenced:"order_shipping_address_location"`
	ShippingAddressPhone         string    `protobuf:"bytes,28,opt,name=shipping_address_phone,json=shippingAddressPhone,proto3" json:"shipping_address_phone,omitempty"`
	ShippingAddressSameAsBilling bool      `protobuf:"varint,29,opt,name=shipping_address_same_as_billing,json=shippingAddressSameAsBilling,proto3" json:"shipping_address_same_as_billing,omitempty"`
	FinalGrandTotal              int64     `protobuf:"varint,30,opt,name=final_grand_total,json=finalGrandTotal,proto3" json:"final_grand_total,omitempty"`
	ShippingFees                 int64     `protobuf:"varint,31,opt,name=shipping_fees,json=shippingFees,proto3" json:"shipping_fees,omitempty"`
	ShippingMethod               string    `protobuf:"bytes,32,opt,name=shipping_method,json=shippingMethod,proto3" json:"shipping_method,omitempty"`
	WillBePaidLater              bool      `protobuf:"varint,33,opt,name=will_be_paid_later,json=willBePaidLater,proto3" json:"will_be_paid_later,omitempty"`
	PaymentTransactionId         string    `protobuf:"bytes,34,opt,name=payment_transaction_id,json=paymentTransactionId,proto3" json:"payment_transaction_id,omitempty"`
	// @inject_tag: cb_referenced:"order_product"
	Product *Product `protobuf:"bytes,35,opt,name=product,proto3" json:"product,omitempty" cb_referenced:"order_product"`
	// @inject_tag: cb_referenced:"order_store"
	Store                *Store   `protobuf:"bytes,36,opt,name=store,proto3" json:"store,omitempty" cb_referenced:"order_store"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_23892fbc74a85022, []int{6}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Order) GetCreationDate() string {
	if m != nil {
		return m.CreationDate
	}
	return ""
}

func (m *Order) GetModificationDate() string {
	if m != nil {
		return m.ModificationDate
	}
	return ""
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetPaymentMethod() string {
	if m != nil {
		return m.PaymentMethod
	}
	return ""
}

func (m *Order) GetInvoiceNumber() string {
	if m != nil {
		return m.InvoiceNumber
	}
	return ""
}

func (m *Order) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Order) GetCardholderName() string {
	if m != nil {
		return m.CardholderName
	}
	return ""
}

func (m *Order) GetCreditCardLast4Digits() string {
	if m != nil {
		return m.CreditCardLast4Digits
	}
	return ""
}

func (m *Order) GetBillingAddress() *Location {
	if m != nil {
		return m.BillingAddress
	}
	return nil
}

func (m *Order) GetBillingAddressName() string {
	if m != nil {
		return m.BillingAddressName
	}
	return ""
}

func (m *Order) GetBillingAddressPhone() string {
	if m != nil {
		return m.BillingAddressPhone
	}
	return ""
}

func (m *Order) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Order) GetShippingAddressName() string {
	if m != nil {
		return m.ShippingAddressName
	}
	return ""
}

func (m *Order) GetShippingAddress() *Location {
	if m != nil {
		return m.ShippingAddress
	}
	return nil
}

func (m *Order) GetShippingAddressPhone() string {
	if m != nil {
		return m.ShippingAddressPhone
	}
	return ""
}

func (m *Order) GetShippingAddressSameAsBilling() bool {
	if m != nil {
		return m.ShippingAddressSameAsBilling
	}
	return false
}

func (m *Order) GetFinalGrandTotal() int64 {
	if m != nil {
		return m.FinalGrandTotal
	}
	return 0
}

func (m *Order) GetShippingFees() int64 {
	if m != nil {
		return m.ShippingFees
	}
	return 0
}

func (m *Order) GetShippingMethod() string {
	if m != nil {
		return m.ShippingMethod
	}
	return ""
}

func (m *Order) GetWillBePaidLater() bool {
	if m != nil {
		return m.WillBePaidLater
	}
	return false
}

func (m *Order) GetPaymentTransactionId() string {
	if m != nil {
		return m.PaymentTransactionId
	}
	return ""
}

func (m *Order) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Order) GetStore() *Store {
	if m != nil {
		return m.Store
	}
	return nil
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Slug                 string   `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug,omitempty"`
	Price                int64    `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	SalePrice            int64    `protobuf:"varint,8,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"`
	CurrencyId           int64    `protobuf:"varint,9,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	OnSale               int64    `protobuf:"varint,10,opt,name=on_sale,json=onSale,proto3" json:"on_sale,omitempty"`
	Status               string   `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_23892fbc74a85022, []int{7}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Product) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetSalePrice() int64 {
	if m != nil {
		return m.SalePrice
	}
	return 0
}

func (m *Product) GetCurrencyId() int64 {
	if m != nil {
		return m.CurrencyId
	}
	return 0
}

func (m *Product) GetOnSale() int64 {
	if m != nil {
		return m.OnSale
	}
	return 0
}

func (m *Product) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Store struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Store) Reset()         { *m = Store{} }
func (m *Store) String() string { return proto.CompactTextString(m) }
func (*Store) ProtoMessage()    {}
func (*Store) Descriptor() ([]byte, []int) {
	return fileDescriptor_23892fbc74a85022, []int{8}
}

func (m *Store) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Store.Unmarshal(m, b)
}
func (m *Store) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Store.Marshal(b, m, deterministic)
}
func (m *Store) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Store.Merge(m, src)
}
func (m *Store) XXX_Size() int {
	return xxx_messageInfo_Store.Size(m)
}
func (m *Store) XXX_DiscardUnknown() {
	xxx_messageInfo_Store.DiscardUnknown(m)
}

var xxx_messageInfo_Store proto.InternalMessageInfo

func (m *Store) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Store) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Store) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Profile)(nil), "models.Profile")
	proto.RegisterType((*Status)(nil), "models.Status")
	proto.RegisterType((*School)(nil), "models.School")
	proto.RegisterType((*Location)(nil), "models.Location")
	proto.RegisterType((*Photo)(nil), "models.Photo")
	proto.RegisterType((*Event)(nil), "models.Event")
	proto.RegisterType((*Order)(nil), "models.Order")
	proto.RegisterType((*Product)(nil), "models.Product")
	proto.RegisterType((*Store)(nil), "models.Store")
}

func init() { proto.RegisterFile("models/company.proto", fileDescriptor_23892fbc74a85022) }

var fileDescriptor_23892fbc74a85022 = []byte{
	// 1432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x57, 0x5f, 0x6f, 0x13, 0x49,
	0x12, 0x97, 0x93, 0xf8, 0x5f, 0x39, 0xb6, 0x93, 0x26, 0x40, 0xc3, 0x01, 0x31, 0xe6, 0x80, 0xdc,
	0x71, 0x0a, 0x27, 0x8e, 0x3b, 0xe9, 0x74, 0x4f, 0x09, 0x1c, 0x2b, 0x24, 0xc2, 0x66, 0x9d, 0xb0,
	0xd2, 0x3e, 0x8d, 0xda, 0x33, 0x1d, 0xbb, 0xc5, 0xcc, 0xf4, 0x6c, 0x77, 0x8f, 0x91, 0x79, 0x5b,
	0xed, 0xf3, 0x7e, 0x86, 0xfd, 0x28, 0xfb, 0x61, 0xf6, 0x8b, 0xac, 0xaa, 0xba, 0xc7, 0xff, 0x02,
	0xda, 0x37, 0xd7, 0xaf, 0x7e, 0x55, 0x5d, 0xff, 0xba, 0x7a, 0x0c, 0x07, 0x99, 0x4e, 0x64, 0x6a,
	0x9f, 0xc7, 0x3a, 0x2b, 0x44, 0x3e, 0x3f, 0x2e, 0x8c, 0x76, 0x9a, 0x35, 0x3c, 0x3a, 0xfc, 0xbd,
	0x09, 0xcd, 0x73, 0xa3, 0xaf, 0x54, 0x2a, 0xd9, 0x1d, 0x68, 0x89, 0xb1, 0x2e, 0x5d, 0x94, 0x49,
	0x5e, 0x1b, 0xd4, 0x8e, 0xda, 0xa3, 0x26, 0xc9, 0x67, 0x92, 0x3d, 0x00, 0x10, 0xb1, 0x53, 0x33,
	0xe5, 0x94, 0xb4, 0x7c, 0x6b, 0xb0, 0x7d, 0xd4, 0x1e, 0xad, 0x20, 0xec, 0x19, 0xec, 0x8b, 0xab,
	0x2b, 0x95, 0x2a, 0xe1, 0x94, 0xce, 0xa3, 0x58, 0x97, 0xb9, 0xe3, 0xdb, 0x83, 0xda, 0xd1, 0xce,
	0x68, 0x6f, 0x45, 0xf1, 0x0a, 0x71, 0x76, 0x17, 0x5a, 0x63, 0x65, 0xdc, 0x34, 0x11, 0x73, 0xbe,
	0x43, 0xe7, 0x2c, 0x64, 0xf6, 0x18, 0x7a, 0x57, 0x62, 0xa6, 0x8d, 0x72, 0x32, 0x1a, 0x6b, 0xfd,
	0xd1, 0xf2, 0x3a, 0x1d, 0xd6, 0xad, 0xd0, 0x53, 0x04, 0xd9, 0x53, 0xe8, 0x2f, 0x68, 0x99, 0x9e,
	0x61, 0x50, 0x0d, 0xe2, 0x2d, 0xac, 0xcf, 0x08, 0x5d, 0xf3, 0x97, 0x95, 0x56, 0xc5, 0xbc, 0xb9,
	0xee, 0xef, 0x0c, 0xc1, 0x35, 0x7f, 0x3f, 0x96, 0xda, 0x49, 0xcb, 0x5b, 0xeb, 0xfe, 0xbe, 0x23,
	0x94, 0xfd, 0x1d, 0xf6, 0x17, 0x44, 0x37, 0x8b, 0xec, 0x54, 0x4b, 0xcb, 0xdb, 0x44, 0x5d, 0x78,
	0xb8, 0x9c, 0x5d, 0x20, 0xcc, 0xee, 0x03, 0x5c, 0x29, 0x63, 0x5d, 0x94, 0x8b, 0x4c, 0x72, 0xa0,
	0x4c, 0xdb, 0x84, 0xbc, 0x17, 0x99, 0x64, 0xf7, 0xa0, 0xad, 0x72, 0x27, 0x8d, 0xb4, 0xce, 0xf2,
	0x0e, 0xb9, 0x58, 0x02, 0xec, 0x18, 0x6e, 0x28, 0x1b, 0x89, 0xa2, 0x48, 0x55, 0xec, 0x8b, 0x5a,
	0x5a, 0x69, 0xf8, 0xee, 0xa0, 0x76, 0xd4, 0x1a, 0xed, 0x2b, 0x7b, 0xb2, 0xd4, 0x7c, 0xb0, 0xd2,
	0xb0, 0xbf, 0x40, 0x3b, 0x15, 0xd5, 0x59, 0x5d, 0x5f, 0x55, 0x04, 0xe8, 0xa8, 0x43, 0xe8, 0xe4,
	0x18, 0x7e, 0x68, 0x4c, 0x8f, 0x1a, 0x03, 0x04, 0xf9, 0x96, 0x3c, 0x81, 0x7e, 0xa1, 0x62, 0x57,
	0x1a, 0x19, 0x8d, 0xd5, 0x24, 0x2a, 0x4d, 0xca, 0xfb, 0xe4, 0xa3, 0x1b, 0xe0, 0x53, 0x35, 0xf9,
	0x60, 0x52, 0x4c, 0xbf, 0xe2, 0xd9, 0x4c, 0xa4, 0x29, 0x31, 0xf7, 0x88, 0x59, 0x39, 0xb8, 0x40,
	0x1c, 0xb9, 0x87, 0xd0, 0xa9, 0xb8, 0xc8, 0xda, 0x27, 0x16, 0x04, 0x08, 0x09, 0x4f, 0xa1, 0x5f,
	0xe8, 0x54, 0x39, 0x15, 0x8b, 0x34, 0x9a, 0x29, 0xf9, 0xc9, 0x72, 0xe6, 0x8b, 0xbe, 0x80, 0xbf,
	0x47, 0x14, 0x07, 0xc6, 0xc8, 0x54, 0x4d, 0x94, 0xce, 0xf9, 0x0d, 0x9f, 0x5a, 0x25, 0xb3, 0x87,
	0xb0, 0x6b, 0xe3, 0xa9, 0xd6, 0x69, 0xc8, 0xed, 0x80, 0x72, 0xeb, 0x78, 0xcc, 0x27, 0x77, 0x1f,
	0xe0, 0x13, 0xc6, 0xea, 0x09, 0x37, 0x89, 0xd0, 0x46, 0xa4, 0xca, 0xbd, 0x61, 0x9d, 0x70, 0xa5,
	0xe5, 0xb7, 0x06, 0xb5, 0xa3, 0xce, 0x8b, 0xde, 0xb1, 0xbf, 0x1b, 0xc7, 0x17, 0x84, 0x8e, 0x82,
	0x96, 0xfd, 0x1b, 0x7a, 0x85, 0x51, 0x99, 0x30, 0xf3, 0xc8, 0x7b, 0xe7, 0xb7, 0x37, 0xf8, 0x84,
	0x8e, 0xba, 0x81, 0xe5, 0x45, 0xf6, 0x1c, 0x3a, 0x53, 0x35, 0x99, 0x56, 0x36, 0xfc, 0x8b, 0x36,
	0x80, 0x94, 0x60, 0xf0, 0x0f, 0x68, 0xa5, 0xda, 0x77, 0x96, 0xdf, 0x21, 0xf6, 0x5e, 0xc5, 0x7e,
	0x17, 0xf0, 0xd1, 0x82, 0xc1, 0x1e, 0x41, 0xbd, 0x98, 0x6a, 0xa7, 0xf9, 0x5d, 0xa2, 0x76, 0x2b,
	0xea, 0x39, 0x82, 0x23, 0xaf, 0x1b, 0x9e, 0x40, 0xc3, 0x27, 0xc3, 0x6e, 0x2d, 0x92, 0xf5, 0x37,
	0xbc, 0x4a, 0xee, 0x10, 0x3a, 0x65, 0x91, 0x08, 0x9c, 0x6a, 0x95, 0x49, 0xbe, 0xe5, 0x9b, 0xe5,
	0xa1, 0x4b, 0x95, 0xc9, 0x61, 0x06, 0x8d, 0x10, 0xdf, 0x13, 0xe8, 0xc5, 0x3a, 0x8f, 0x65, 0xee,
	0x0c, 0x85, 0x80, 0xae, 0xa8, 0x6b, 0xeb, 0x28, 0xb6, 0x77, 0x62, 0x44, 0x52, 0xfa, 0xe9, 0x9d,
	0x4b, 0x61, 0xc8, 0xed, 0xce, 0xa8, 0xb7, 0x84, 0x7f, 0x90, 0xc2, 0x30, 0x06, 0x3b, 0x34, 0xb5,
	0xdb, 0x74, 0x28, 0xfd, 0x1e, 0xfe, 0x54, 0x83, 0x56, 0x95, 0x2d, 0x12, 0x62, 0xe5, 0xe6, 0x21,
	0x64, 0xfa, 0xcd, 0x38, 0x34, 0xa9, 0x9f, 0x66, 0x1e, 0x82, 0xad, 0x44, 0x76, 0x00, 0x75, 0x4c,
	0xaa, 0xf2, 0xe7, 0x05, 0x9f, 0xb8, 0x91, 0xd2, 0x85, 0x95, 0x13, 0x24, 0x5c, 0x7a, 0x9f, 0x55,
	0x11, 0xc5, 0x3a, 0x91, 0xbc, 0xee, 0x1d, 0x7d, 0x56, 0xc5, 0x2b, 0x9d, 0xc8, 0xe1, 0x6f, 0x35,
	0xa8, 0x53, 0x19, 0xe9, 0x30, 0x51, 0x50, 0x47, 0xc2, 0x62, 0x0c, 0x22, 0xce, 0x56, 0x6c, 0xa4,
	0x70, 0x32, 0x89, 0x84, 0x0b, 0x91, 0xb4, 0x03, 0x72, 0xe2, 0x70, 0x3a, 0x53, 0x61, 0x26, 0x32,
	0xb2, 0xba, 0x34, 0x71, 0x15, 0x52, 0x87, 0xb0, 0x0b, 0x82, 0x30, 0xb9, 0x54, 0xe5, 0x1f, 0x43,
	0x58, 0xf4, 0x9b, 0x3d, 0x82, 0x6e, 0x26, 0x13, 0x55, 0x66, 0x95, 0x9d, 0x8f, 0x6c, 0xd7, 0x83,
	0xc1, 0x10, 0x27, 0x9f, 0xee, 0x60, 0xe0, 0x34, 0xbc, 0x6f, 0xc2, 0x3c, 0x65, 0xf8, 0xcb, 0x16,
	0xd4, 0xff, 0x3f, 0x93, 0xb9, 0x63, 0x03, 0xe8, 0x24, 0xd2, 0xc6, 0x46, 0xad, 0x66, 0xb1, 0x0a,
	0x61, 0x21, 0x64, 0x9e, 0xac, 0xb6, 0xbf, 0x29, 0xf3, 0x04, 0x7b, 0x8f, 0x2a, 0x5b, 0x8e, 0x23,
	0x37, 0x2f, 0xaa, 0x0c, 0x9a, 0xb6, 0x1c, 0x5f, 0xce, 0x0b, 0x8a, 0x9e, 0xe0, 0x10, 0xbd, 0x0b,
	0xd8, 0x54, 0x5b, 0x17, 0x82, 0xa6, 0xdf, 0xcb, 0x31, 0x6d, 0x7c, 0x7d, 0x4c, 0xd7, 0x26, 0xbf,
	0xf9, 0xa7, 0x93, 0x5f, 0x8d, 0x4d, 0x6b, 0x39, 0x36, 0xd8, 0x0e, 0xeb, 0x84, 0x71, 0x3e, 0x8d,
	0xb6, 0x6f, 0x07, 0x21, 0x34, 0xc4, 0xbf, 0xb6, 0xa0, 0xfe, 0xad, 0x49, 0xa4, 0xc1, 0x21, 0x71,
	0xfa, 0xa3, 0xac, 0x2a, 0xe1, 0x05, 0xac, 0x3b, 0xf5, 0x0e, 0x07, 0x16, 0x27, 0x3f, 0x14, 0x62,
	0xb7, 0x02, 0x5f, 0xe3, 0x24, 0x3d, 0x83, 0xfd, 0x4c, 0x27, 0xea, 0xaa, 0xda, 0xcb, 0xc9, 0x72,
	0xd6, 0xf6, 0x56, 0x15, 0xaf, 0x17, 0x63, 0x47, 0xf7, 0x6d, 0x67, 0xed, 0xbe, 0x3d, 0x86, 0x5e,
	0x21, 0xe6, 0x99, 0xcc, 0xf1, 0xb5, 0x75, 0x53, 0x9d, 0x84, 0x6a, 0x75, 0x03, 0x7a, 0x46, 0x20,
	0xd2, 0x54, 0x3e, 0xd3, 0x2a, 0x96, 0x51, 0x5e, 0x66, 0x63, 0x69, 0x42, 0x97, 0xbb, 0x01, 0x7d,
	0x4f, 0x20, 0x66, 0x23, 0x33, 0xa1, 0x52, 0xaa, 0x5a, 0x7b, 0xe4, 0x05, 0xbc, 0x80, 0xb1, 0x30,
	0xc9, 0x54, 0xa7, 0x89, 0x34, 0xd1, 0x4a, 0xad, 0x7a, 0x4b, 0x98, 0x9e, 0x87, 0xff, 0xc0, 0xed,
	0xd8, 0xc8, 0x44, 0xb9, 0x08, 0x15, 0x11, 0x3e, 0x1b, 0x2f, 0x13, 0x35, 0x51, 0xce, 0x86, 0x12,
	0xde, 0xf4, 0xea, 0x57, 0xc2, 0x24, 0xef, 0x96, 0x4a, 0xf6, 0x5f, 0xe8, 0x8f, 0x55, 0x9a, 0xaa,
	0x7c, 0x12, 0x89, 0x24, 0x31, 0xd2, 0x5a, 0x7a, 0xe5, 0xbe, 0xd4, 0xb6, 0x5e, 0x20, 0x9e, 0x78,
	0x1e, 0xfb, 0x27, 0x1c, 0x6c, 0x98, 0xfa, 0x00, 0x3b, 0x74, 0x1e, 0x5b, 0x67, 0x53, 0x90, 0x2f,
	0xe0, 0xe6, 0xa6, 0x45, 0x31, 0xd5, 0xb9, 0xe4, 0x8c, 0x4c, 0x6e, 0xac, 0x9b, 0x9c, 0xa3, 0x0a,
	0xeb, 0x42, 0x8f, 0x5c, 0x78, 0x35, 0xbc, 0x80, 0x9e, 0xec, 0x54, 0x15, 0xc5, 0xb5, 0xc3, 0x0f,
	0xbc, 0xa7, 0x4a, 0xb9, 0x7a, 0xfa, 0xff, 0x60, 0x6f, 0xd3, 0x86, 0x5e, 0x92, 0x2f, 0xe5, 0xda,
	0xdf, 0x70, 0xc0, 0x5e, 0xc2, 0xad, 0x6b, 0x07, 0xfa, 0xd8, 0xef, 0xd1, 0x89, 0x07, 0x1b, 0x06,
	0x3e, 0xf8, 0x37, 0x30, 0xb8, 0x66, 0x65, 0x45, 0x26, 0x23, 0x61, 0xa3, 0x90, 0x2c, 0xbf, 0x4f,
	0x9f, 0x03, 0xf7, 0x36, 0xec, 0x2f, 0x44, 0x26, 0x4f, 0xec, 0xa9, 0xe7, 0xd0, 0x27, 0x8b, 0xca,
	0x45, 0x1a, 0x4d, 0x8c, 0xc0, 0x0b, 0xae, 0x9d, 0x48, 0xf9, 0x83, 0x41, 0xed, 0x68, 0x7b, 0xd4,
	0x27, 0xc5, 0x37, 0x88, 0x5f, 0x22, 0x8c, 0x17, 0x60, 0x71, 0xe6, 0x95, 0x94, 0x96, 0x1f, 0x12,
	0x6f, 0xb7, 0x02, 0xdf, 0x48, 0x49, 0x8b, 0x7d, 0x41, 0x0a, 0xc3, 0x3b, 0xf0, 0x73, 0x55, 0xc1,
	0x61, 0x7a, 0x9f, 0x01, 0xfb, 0xa4, 0xd2, 0x34, 0x1a, 0xcb, 0xa8, 0x10, 0x0a, 0x07, 0xcb, 0x49,
	0xc3, 0x1f, 0x52, 0xcc, 0x7d, 0xd4, 0x9c, 0xca, 0x73, 0xa1, 0x92, 0x77, 0x08, 0x63, 0x91, 0xaa,
	0x1b, 0xe1, 0x8c, 0xc8, 0x2d, 0x7e, 0x5d, 0xea, 0x3c, 0x52, 0x09, 0x1f, 0xfa, 0x22, 0x05, 0xed,
	0xe5, 0x52, 0xf9, 0x36, 0x61, 0x7f, 0x83, 0x66, 0x61, 0x74, 0x52, 0xc6, 0x8e, 0x3f, 0xa2, 0x76,
	0xf4, 0x17, 0x9b, 0xc5, 0xc3, 0xa3, 0x4a, 0x8f, 0x2b, 0xc8, 0x3a, 0x6d, 0x24, 0xff, 0xeb, 0xfa,
	0x0a, 0xba, 0x40, 0x70, 0xe4, 0x75, 0xc3, 0x9f, 0xb7, 0xe8, 0x7b, 0x98, 0x0c, 0x7a, 0xb0, 0xa5,
	0x92, 0xb0, 0x20, 0xb6, 0x54, 0xc2, 0x6e, 0x43, 0x13, 0xbf, 0xc1, 0x30, 0x24, 0xbf, 0x17, 0x1a,
	0x28, 0xbe, 0x4d, 0x16, 0x9b, 0x68, 0x67, 0x65, 0x13, 0x6d, 0x2c, 0xdc, 0xfa, 0xf5, 0x85, 0xcb,
	0x60, 0xc7, 0xa6, 0xe5, 0x24, 0xdc, 0x68, 0xfa, 0x8d, 0x03, 0x5b, 0x18, 0x15, 0x4b, 0xba, 0xc8,
	0xdb, 0x23, 0x2f, 0xd0, 0x56, 0x13, 0xa9, 0x8c, 0xbc, 0xaa, 0x45, 0xaa, 0x36, 0x22, 0xe7, 0xa4,
	0x3e, 0x84, 0x4e, 0x5c, 0x1a, 0x23, 0xf3, 0x78, 0x8e, 0xb1, 0xb5, 0x49, 0x0f, 0x15, 0xf4, 0x96,
	0x02, 0xd7, 0x79, 0x84, 0x06, 0x74, 0x3f, 0xb7, 0x47, 0x0d, 0x9d, 0x5f, 0x88, 0x74, 0x75, 0x3b,
	0x75, 0x56, 0xb7, 0xd3, 0xf0, 0x0c, 0xea, 0x54, 0x95, 0x6b, 0x25, 0xa8, 0x32, 0xdd, 0xfa, 0x7a,
	0xa6, 0xdb, 0xd7, 0x32, 0x1d, 0x37, 0xe8, 0x3f, 0xc7, 0xbf, 0xfe, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x3c, 0x62, 0xf2, 0x94, 0x8b, 0x0c, 0x00, 0x00,
}
